branches:
  only:
    - master
    - /^greenkeeper/.*$/

language: node_js
node_js:
  - node
os:
  - linux

cache:
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify

jobs:
  include:
    # we have multiple jobs to execute using just a single stage
    # but we can pass group name via environment variable to Cypress test runner
    - stage: lint
      name: "JavaScript linting"
      script: npm run lint
    - stage: test
      name: "Integration Tests"
      script:
        - npm start -- --silent &
        - npm run cy:run
        # after all tests finish running we need
        # to kill all background jobs (like "npm start &")
        - kill $(jobs -p) || true
