branches:
  only:
    - master
    - /^greenkeeper/.*$/

language: node_js
node_js:
  - node
os:
  - linux

cache:
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify

addons:
  chrome: stable

jobs:
  include:
    - stage: lint
      name: "JavaScript linting"
      script: npm run lint

    - stage: test
      name: "Integration Tests"
      script:
        - npm start -- --silent &
        # We have to use Chrome due to
        # https://github.com/ComFreek/polynomial-interpolation-web-gui/issues/2
        - npm run cy:run -- --browser chrome
        # after all tests finish running we need to kill all background jobs (like "npm start &")
        - kill $(jobs -p) || true
