branches:
  only:
    - master
    - /^greenkeeper/.*$/

language: node_js
node_js:
  - node
os:
  - linux

cache:
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify

addons:
  chrome: stable

script:
  - node ./check-geogebra-apps-version.js || travis_terminate 1
  - npm run lint || travis_terminate 1
  - npm test
  - kill $(jobs -p) || true

deploy:
  provider: pages
  local-dir: src
  skip-cleanup: true
  github-token: $GITHUB_PAGES_DEPLOYMENT_TOKEN
  keep-history: true
  on:
    branch: master
  target-branch: gh-pages
