branches:
  only:
    - master
    - /^greenkeeper/.*$/

language: node_js
node_js:
  # Node 10.3+ includes npm@6 which has good "npm ci" command
  - 10.8
  - node
os:
  - linux

cache:
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify

script:
  - npm run lint

defaults: &defaults
  script:
    - npm start -- --silent &
    - npm run cy:run -- --record --parallel --group $STAGE_NAME
    # after all tests finish running we need
    # to kill all background jobs (like "npm start &")
    - kill $(jobs -p) || true

jobs:
  include:
    # we have multiple jobs to execute using just a single stage
    # but we can pass group name via environment variable to Cypress test runner
    - stage: test
      env:
        - STAGE_NAME=1x-electron
      <<: *defaults
    # run tests in parallel by including several test jobs with same name variable
    - stage: test
      env:
        - STAGE_NAME=4x-electron
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME=4x-electron
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME=4x-electron
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME=4x-electron
      <<: *defaults
